# Generated by Django 5.0.3 on 2024-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
