# Generated by Django 5.0.3 on 2024-04-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wishlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
    ]
